#!/usr/bin/env bash
# Run the production stack locally (see deploy/local/compose.yml).
#   deploy/local/stack.sh up -d --build     start (first run generates keys)
#   deploy/local/stack.sh logs -f app       follow the app
#   deploy/local/stack.sh exec -T db psql -U supabase_admin -d postgres -v staff_email=you@example.com < deploy/bootstrap.sql
#   deploy/local/stack.sh down -v           stop and delete the local data
# Then open http://ctc.localhost:8086 (sign-in emails: http://127.0.0.1:8087).
set -euo pipefail
cd "$(dirname "$0")/../.."
ENV_FILE=deploy/local/.env

if [ ! -f "$ENV_FILE" ]; then
  echo "stack.sh: generating $ENV_FILE"
  {
    echo "# Generated by deploy/local/stack.sh for local rehearsal only."
    echo "DOCKERHUB_USERNAME=local"
    echo "IMAGE_TAG=local"
    echo "HOST_APP_PORT=8084"
    echo "HOST_KONG_PORT=8085"
    echo "POSTGRES_HOST=db"
    echo "POSTGRES_PORT=5432"
    echo "POSTGRES_DB=postgres"
    echo "POSTGRES_PASSWORD=$(openssl rand -hex 32)"
    echo "JWT_EXPIRY=3600"
    deploy/gen-keys.sh
    echo "SITE_URL=http://ctc.localhost:8086"
    echo "API_EXTERNAL_URL=http://ctc.localhost:8086"
    echo "ADDITIONAL_REDIRECT_URLS=http://ctc.localhost:8086/**"
    echo "DISABLE_SIGNUP=false"
    echo "ENABLE_EMAIL_SIGNUP=true"
    echo "ENABLE_EMAIL_AUTOCONFIRM=false"
    echo "SMTP_ADMIN_EMAIL=noreply@ctc.localhost"
    echo "SMTP_HOST=mailpit"
    echo "SMTP_PORT=1025"
    echo "SMTP_USER="
    echo "SMTP_PASS="
    echo "SMTP_SENDER_NAME=CTC Scoring (local)"
    echo "PGRST_DB_SCHEMAS=public,graphql_public"
  } >"$ENV_FILE"
  chmod 600 "$ENV_FILE"
fi

exec docker compose -p ctc-scoring-local --env-file "$ENV_FILE" \
  -f docker-compose.yml -f deploy/local/compose.yml "$@"
